apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: build/konflux-patch.sh
    build.appstudio.openshift.io/repo: https://github.com/stolostron/gatekeeper?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "release-3.17" && (".tekton/gatekeeper-*.yaml".pathChanged() || "Dockerfile".pathChanged() ||  "build/Dockerfile.rhtap".pathChanged() || "go.{mod,sum}".pathChanged() ||  "main.go".pathChanged() || "{apis,pkg,vendor}/***".pathChanged())
  labels:
    appstudio.openshift.io/application: gatekeeper-operator-3-17
    appstudio.openshift.io/component: gatekeeper-3-17
    pipelines.appstudio.openshift.io/type: build
  name: gatekeeper-3-17-on-push
  namespace: gatekeeper-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/gatekeeper-tenant/gatekeeper-operator-3-17/gatekeeper-3-17:{{revision}}
    - name: path-context
      value: .
    - name: dockerfile
      value: build/Dockerfile.rhtap
    - name: hermetic
      value: 'true'
    - name: build-source-image
      value: 'true'
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-gatekeeper-3-17
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
